name: build
on:
  push:
    branches:
      - main
  schedule:
    # Run this script every 1 hrs
    #  */m hr day month day_of_week
    - cron:  '0 */1 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description Tag'  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run
        run: |
          npm install
          npm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
